### ISSUE TITLE
Is the project still beeing worked on?

### ISSUE THREAD

**Issue by sphrases** [ordazgustavo/here-maps-react#19]
Hey, I stumbled on this project while looking for a way to render a map in react. 

I cant get the app to work sadly (the whole key procedure changed, maybe this is breaking)
Is anyone still working on the project?

**Comment by shyr1punk** [comment]
@sphrases I'm publish new version 2.0 with update to API v 3.1 (details here https://github.com/shyr1punk/here-maps-react/pull/1/files)
