### ISSUE TITLE
ReferenceError: H is not defined

### ISSUE THREAD

**Issue by TahinDani** [ordazgustavo/here-maps-react#9]
I get the following error when I try to use the HEREMap component:
Uncaught (in promise) ReferenceError: H is not defined
    at getPlatform (index.es.js:365)
    at HEREMap._this.createMap (index.es.js:393)
    at index.es.js:449
    at index.es.js:131

**Comment by jimenaCabrejas** [comment]
Same issue here.

**Comment by leireNN** [comment]
Same here

**Comment by MrXo** [comment]
You have to add this as first line of your javascript file.

```
/*global H*/
import React from 'react'
...
```

It is actually described in this tutorial but the actual solution is missing: https://developer.here.com/blog/use-here-interactive-maps-with-reactjs-to-pick-a-theme
Fortunately my colleague solved the issue already some time ago.

**Comment by ordazgustavo** [comment]
This should be resolved on the beta version

You can install it with 

```bash
npm install here-maps-react@beta
```
If you wish
